package:
  name: perses-dev
  version: !!str 0.0.0

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - openmm-dev
    - parmed-dev
    - numpy
    - scipy
    - openmoltools-dev
    - alchemy-dev
    - numexpr
    - openmmtools-dev
    - pymbar
    - autograd

  run:
    - python
    - openmm-dev
    - parmed-dev
    - numpy
    - scipy
    - openmoltools-dev
    - alchemy-dev
    - numexpr
    - openmmtools-dev
    - pymbar
    - autograd

test:
  requires:
    - nose
    - openmmtools-dev
    - pymbar
  imports:
    - perses


about:
  home: https://github.com/choderalab/perses
  license: GNU Lesser General Public License v2 or later (LGPLv2+)
