name: perses
channels:
    - omnia
dependencies:
    - python
    - setuptools
    - numpy
    - scipy
    - numexpr
    - autograd
    - pymbar
    - openmm
    - parmed
    - openmoltools
    - alchemy
    - openmmtools
    - numba
    - netcdf4
    - matplotlib
    - seaborn
    - pdbfixer
    - mdtraj
    - parmed
    - pdbfixer
    - numpydoc
